version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/Ex33?allowPublicKeyRetrieval=true
    depends_on:
        - mysql
    volumes:
      - .m2:/root/.m2

  mysql:
    image: "mysql:8.0.34"
    restart: always
    ports:
      - "3306:3306"
    networks:
        - springapimysql-net
    environment:
      - MYSQL_DATABASE=Ex33
      - MYSQL_PASSWORD=secret1
      - MYSQL_ROOT_PASSWORD=secret1

networks:
    springapimysql-net:


